//
// Created by nunol on 1/4/2022.
//

#ifndef GL_ENGINE_INCLUDE_ENGINE_GRAPHICS_DESCRIPTORS_HPP_
#define GL_ENGINE_INCLUDE_ENGINE_GRAPHICS_DESCRIPTORS_HPP_

#endif //GL_ENGINE_INCLUDE_ENGINE_GRAPHICS_DESCRIPTORS_HPP_
